#!/usr/bin/zsh

TALK_DIR="${HOME}/projects/chaotikum/shell-talk"
cd "$TALK_DIR"
source "$TALK_DIR/shell-talk.sh"
source "$TALK_DIR/slides-nook.sh"
source "$TALK_DIR/keyboard.sh"
prepare_terminal

tmux new-session -s shell-magic -dn presentation
tmux new-window  -t shell-magic:1 -n control

tmux send-keys -t shell-magic:0 "cd ${HOME}/projects/chaotikum/shell-talk" C-m
tmux send-keys -t shell-magic:0 "source shell-talk.sh" C-m
tmux send-keys -t shell-magic:0 "source slides-nook.sh" C-m
tmux send-keys -t shell-magic:0 "source keyboard.sh" C-m
tmux send-keys -t shell-magic:0 "prepare_terminal" C-m

tmux send-keys -t shell-magic:1 "cd ${HOME}/projects/chaotikum/shell-talk" C-m

tmux set-option -t shell-magic status 0

tmux select-window -t shell-magic:0
tmux attach-session -t shell-magic
